# Generated by Django 6.1.1 on 2026-09-12 14:56

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_candidate_created_at_candidate_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.Candidate.resume_upload_path,
                validators=[core.validators.validate_resume_file],
            ),
        ),
    ]
