# Generated by Django 6.1.1 on 2026-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_candidate_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(
                choices=[
                    ("fresher", "Fresher"),
                    ("0-1", "0-1 years"),
                    ("1-3", "1-3 years"),
                    ("3-5", "3-5 years"),
                    ("5+", "5+ years"),
                ],
                default="fresher",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("remote", "Remote"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.TextField(
                default="", help_text="Comma-separated list, e.g. 'Python, Django, SQL'"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
