# Generated by Django 6.1.1 on 2026-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job_experience_job_job_type_job_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("remote", "Remote"),
                ],
                db_index=True,
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "-posted_at"], name="job_status_posted_idx"
            ),
        ),
    ]
