# Generated by Django 6.1.1 on 2026-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_job_featured_alter_job_job_type_alter_job_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AddField(
            model_name="application",
            name="resume_snapshot",
            field=models.FileField(
                blank=True, null=True, upload_to="application_resumes/"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "job")},
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate", "status"], name="core_applic_candida_dc4f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "status"], name="core_applic_job_id_472dfd_idx"
            ),
        ),
    ]
