# Generated by Django 6.1.1 on 2026-09-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

OLD_TO_NEW = {
    "pending": "applied",
    "reviewed": "shortlisted",
    "rejected": "rejected",
}
 
 
def migrate_statuses_forward(apps, schema_editor):
    Application = apps.get_model("core", "Application")
    for old, new in OLD_TO_NEW.items():
        Application.objects.filter(status=old).update(status=new)
 
 
def migrate_statuses_backward(apps, schema_editor):
    Application = apps.get_model("core", "Application")
    reverse_map = {v: k for k, v in OLD_TO_NEW.items()}
    for new, old in reverse_map.items():
        Application.objects.filter(status=new).update(status=old)
        
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_application_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("shortlisted", "Shortlisted"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("rejected", "Rejected"),
                    ("selected", "Selected"),
                ],
                default="applied",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="core.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.RunPython(migrate_statuses_forward, migrate_statuses_backward),
    ]
