# Generated by Django 6.1.1 on 2026-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_flag_reason_user_is_flagged_adminactionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ats_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="ats_score_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="ats_scored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="required_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School"),
                    ("bachelors", "Bachelor's Degree"),
                    ("masters", "Master's Degree"),
                    ("phd", "PhD"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
