# Generated by Django 6.1.1 on 2026-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_application_ats_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="auto_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="auto_processing_excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="auto_processing_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="auto_reject_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="auto_shortlist_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
